---
# Example playbook to report Max Write IOPS per host performance on a FlashArray
#
# Execute as follows
# 
# ansible-playbook playbooks/ps_performance_host_live_maxWrite_IOPS.yml -e "writes_per_sec=10000"
# if you want Ansible to report live hosts with Write IOPS > 10000
#
- name: Max Writes IOPS Information on FlashArray
  hosts: localhost
  gather_facts: no

  tasks:
    - name: open session
      uri:
        url: https://{{ arrayurl }}/api/{{ api_version }}/auth/session
        method: POST
        validate_certs: no
        return_content: yes
        body:
          api_token: "{{ array_token }}"
        body_format: json
      register: session

    - name: max writes iops performance
      uri:
        url: https://{{ arrayurl }}/api/{{ api_version }}/host?action=monitor&filter=writes_per_sec>{{ writes_per_sec }}
        method: GET
        validate_certs: no
        HEADER_Cookie: "{{session.set_cookie}}"
        return_content: yes
      ignore_errors: yes
      register: perfdata

    - name: show max writes per host
      debug: msg="{{ perfdata.json }}"

    - name: close session
      uri:
        url: https://{{ arrayurl }}/api/{{ api_version }}/auth/session
        method: DELETE
        validate_certs: no
        return_content: yes
        HEADER_Cookie: "{{session.set_cookie}}"
        register: session_close
