---
# Example playbook to report Read Bandwidth (bytes/sec) volume performance per host on a FlashArray
#
# Execute as follows
#
# ansible-playbook playbooks/ps_performance_volume_ReadBW.yml -e "volname=cdsd003*"
# 
- name: Volume Read BW performance Information on FlashArray
  hosts: localhost
  gather_facts: no

  tasks:
    - name: open session
      uri:
        url: https://{{ arrayurl }}/api/{{ api_version }}/auth/session
        method: POST
        validate_certs: no
        return_content: yes
        body:
          api_token: "{{ array_token }}"
        body_format: json
      register: session

    - name: volume read bw performance
      uri:
        url: https://{{ arrayurl }}/api/{{ api_version }}/volume?action=monitor&names={{ volname }}&sort=output_per_sec
        method: GET
        validate_certs: no
        HEADER_Cookie: "{{session.set_cookie}}"
        return_content: yes
      ignore_errors: yes
      register: voldata

    - name: show volume list
      debug: msg="{{ voldata.json }}"

    - name: close session
      uri:
        url: https://{{ arrayurl }}/api/{{ api_version }}/auth/session
        method: DELETE
        validate_certs: no
        return_content: yes
        HEADER_Cookie: "{{session.set_cookie}}"
        register: session_close
