---
# Example playbook to set timeout session on a FlashArray
#
# Execute as follows
#
# ansible-playbook playbooks/ps_timeout_setup.yml -e "idle_timeout=60"
# 
- name: timeout set on FlashArray
  hosts: localhost
  gather_facts: no

  tasks:
    - name: open session
      uri:
        url: https://{{ arrayurl }}/api/{{ api_version }}/auth/session
        method: POST
        validate_certs: no
        return_content: yes
        body:
          api_token: "{{ array_token }}"
        body_format: json
      register: session

    - name: timeout
      uri:
        url: https://{{ arrayurl }}/api/{{ api_version }}/array?idle_timeout=true
        method: PUT
        validate_certs: no
        HEADER_Cookie: "{{session.set_cookie}}"
        return_content: yes
        body:
          idle_timeout: "{{ idle_timeout }}"
        body_format: json
      ignore_errors: yes
      register: timeoutdata

    - name: show timeout data
      debug: msg="{{ timeoutdata.json }}"

    - name: close session
      uri:
        url: https://{{ arrayurl }}/api/{{ api_version }}/auth/session
        method: DELETE
        validate_certs: no
        return_content: yes
        HEADER_Cookie: "{{session.set_cookie}}"
        register: session_close
